### ISSUE TITLE
[BUG] "test_data" columns are not coerced into string like the "train" data is

### ISSUE THREAD

**Issue by sgujjaABM** [pycaret/pycaret#2195]
**Describe the bug**

**To Reproduce**

Hi, I am getting an error running the setup function with train and test data sets. Can you please help?
```python
clasf = setup(train, target = 'y',n_jobs=-1,test_data=test) 
Traceback (most recent call last):
  File "/home/ec2-user/sgujja/qsar_modeling/repos/fup/qsar_class_pycaret_ppb.py", line 188, in <module>
    clasf = setup(train, target = 'y',n_jobs=-1,test_data=test) #, #numeric_features = features) #,n_jobs=-1,polynomial_features = True, polynomial_degree = 2)
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pycaret/classification.py", line 580, in setup
    return pycaret.internal.tabular.setup(
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 1308, in setup
    test_data = prep_pipe.transform(test_data)
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/sklearn/pipeline.py", line 549, in _transform
    Xt = transform.transform(Xt)
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pycaret/internal/preprocess.py", line 357, in transform
    data = data[self.final_training_columns]
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
There is not enough information here to reproduce the error. Please submit a Minimally Reproducible Example per

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sgujjaABM** [comment]
Hi,

Here's the code used:

```
# Set up our dataset (preprocessing)
clasf = setup(train, target = 'y',n_jobs=5, test_data=test) 

# compare all baseline models and select top 5
top5 = compare_models(n_select = 5)

# tune models
tuned_top5 = [tune_model(i) for i in top5]

# ensemble models
#bagged_top5 = [ensemble_model(i) for i in tuned_top5]

# blend models
blender = blend_models(estimator_list = tuned_top5)

# stack models
stacker = stack_models(estimator_list = tuned_top5)

# automl
best = automl(optimize = 'AUC')
print(best)

# Get train metrics
train_metrics = pull()
print("Train metrics:")
print(train_metrics)

# Deploy Model to generate predictions
test_predictions = predict_model(best)
print(test_predictions.head(5))
# Get test metrics
test_metrics = pull()
print("Test metrics:")
print(test_metrics)

# Predicting on unseen data
test_predictions = predict_model(best, test)
print("Predicting on unseen data:")
print(test_predictions.head(5))

# save model
save_model(best, 'pycaret_best_model')
```

**Comment by ngupta23** [comment]
It is still hard to debug with the incomplete information you have provided (partial error message and no data). Also just a small comment - the code is producing the error at the `setup` stage so you should only provide the code snippet till that point  (when producing a Minimal Reproducible Example). This will help those who are debugging. The rest of the code is not important for the problem being debugged.

From the what you have provided, it seems that there is some column missing in the test data. What was the complete error message? It should tell you the column name that is missing.

```python
raise KeyError(f"{not_found} not in index")
```

**Comment by sgujjaABM** [comment]
Yes, the error comes up at the setup function: the key error comes up on all the columns. It's not clear to me why that is the case. Thanks for helping with this.

```
 File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/ec2-user/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['971', '701', '847', '876', '694', '638', '375', '555', '558', '198', '436', '877', '42', '950', '49', '572', '124', '101', '666', '552', '871', '700', '823', '407', '7', '48', '472', '23', '199', '370', '420', '543', '617', '661', '828', '875', '630', '713', '17', '336', '354', '469', '480', '988', '674', '969', '298', '159', '910', '972', '714', '13', '754', '615', '658', '545', '1018', '100', '55', '945', '502', '392', '295', '306', '330', '373', '902', '284', '914', '514', '610', '510', '864', '151', '588', '865', '283', '999', '491', '4', '1021', '205', '1029', '1017', '249', '363', '501', '346', '312', '562', '285', '200', '974', '900', '10', '850', '1026', '235', '721', '983', '755', '9', '776', '690', '11', '417', '5', '592', '209', '607', '83', '379', '584', '670', '161', '301', '830', '621', '642', '21', '466', '949', '121', '481', '35', '561', '337', '817', '153', '461', '723', '467', '109', '410', '956', '428', '332', '138', '181', '22', '347', '316', '381', '194', '61', '178', '386', '781', '762', '119', '258', '703', '6', '770', '225', '619', '997', '1004', '349', '95', '526', '986', '925', '156', '892', '245', '591', '319', '315', '275', '560', '564', '496', '517', '448', '1014', '401', '192', '430', '232', '799', '967', '527', '498', '654', '551', '227', '16', '242', '362', '104', '234', '291', '909', '90', '536', '509', '474', '760', '724', '726', '51', '603', '650', '310', '190', '518', '813', '0', '576', '709', '602', '62', '414', '380', '422', '473', '655', '565', '885', '108', '239', '113', '165', '669', '671', '785', '987', '30', '570', '338', '447', '928', '229', '777', '872', '893', '708', '523', '1031', '852', '210', '395', '796', '118', '507', '720', '577', '378', '689', '907', '947', '2', '92', '324', '767', '710', '869', '1032', '821', '768', '43', '358', '959', '529', '216', '939', '712', '277', '126', '606', '841', '601', '1', '28', '152', '583', '222', '36', '790', '69', '904', '206', '934', '738', '486', '620', '201', '867', '704', '846', '761', '1003', '960', '150', '1002', '342', '771', '238', '269', '1000', '525', '143', '224', '391', '831', '922', '406', '215', '223', '248', '429', '693', '801', '851', '861', '946', '644', '897', '396', '167', '438', '313', '977', '653', '441', '287', '541', '512', '740', '344', '715', '736', '747', '829', '557', '879', '1007', '533', '67', '539', '79', '633', '648', '125', '843', '412', '63', '212', '751', '752', '369', '635', '456', '196', '962', '147', '521', '727', '1016', '1011', '782', '307', '426', '834', '376', '711', '827', '197', '773', '158', '513', '140', '87', '384', '626', '746', '906', '421', '824', '340', '550', '416', '744', '431', '65', '582', '365', '114', '757', '184', '789', '453', '418', '600', '913', '1027', '244', '838', '186', '490', '651', '750', '3', '963', '532', '32', '802', '873', '111', '492', '886', '978', '75', '408', '89', '419', '544', '261', '681', '106', '493', '733', '915', '976', '678', '110', '763', '263', '266', '46', '45', '970', '921', '80', '361', '34', '538', '394', '891', '91', '281', '680', '368', '333', '836', '193', '292', '944', '97', '302', '797', '597', '117', '860', '930', '982', '609', '169', '1030', '129', '924', '58', '52', '696', '189', '729', '411', '786', '686', '93', '155', '614', '195', '343', '471', '737', '697', '718', '995', '540', '405', '784', '955', '259', '933', '468', '554', '822', '627', '631', '772', '511', '901', '634', '477', '322', '449', '684', '31', '141', '487', '397', '530', '299', '462', '594', '522', '682', '728', '866', '878', '146', '18', '818', '1006', '647', '542', '356', '788', '920', '1012', '329', '387', '731', '795', '722', '76', '912', '219', '57', '59', '374', '695', '432', '359', '787', '691', '566', '56', '314', '882', '942', '484', '844', '475', '326', '457', '569', '599', '157', '311', '437', '820', '398', '393', '389', '84', '60', '679', '164', '183', '508', '732', '458', '837', '334', '716', '348', '745', '929', '919', '705', '24', '656', '1010', '1019', '290', '870', '890', '943', '1001', '1025', '323', '673', '908', '208', '605', '172', '139', '14', '29', '120', '177', '214', '264', '537', '590', '699', '783', '926', '954', '748', '810', '64', '211', '659', '353', '774', '70', '793', '505', '131', '82', '44', '136', '50', '585', '675', '806', '812', '54', '102', '228', '596', '598', '321', '1013', '624', '262', '202', '758', '506', '639', '66', '37', '809', '149', '549', '499', '685', '233', '25', '335', '383', '497', '1008', '218', '665', '154', '372', '377', '116', '204', '445', '896', '966', '253', '519', '832', '985', '175', '652', '993', '105', '660', '688', '534', '868', '916', '825', '778', '683', '559', '296', '612', '765', '589', '442', '270', '12', '464', '325', '220', '1022', '573', '535', '1009', '979', '168', '853', '182', '286', '862', '163', '246', '160', '677', '74', '293', '38', '935', '973', '257', '546', '339', '171', '918', '123', '444', '858', '646', '975', '483', '749', '800', '816', '948', '273', '399', '640', '303', '403', '409', '443', '470', '965', '593', '272', '1023', '574', '40', '203', '142', '923', '250', '185', '961', '72', '958', '482', '173', '702', '495', '839', '350', '657', '991', '115', '791', '390', '725', '888', '103', '8', '855', '27', '402', '81', '637', '805', '221', '769', '71', '516', '367', '162', '500', '668', '992', '664', '911', '623', '932', '622', '328', '134', '581', '388', '632', '794', '854', '575', '779', '39', '268', '815', '953', '351', '423', '826', '132', '520', '317', '845', '454', '364', '662', '357', '842', '96', '460', '237', '53', '145', '226', '191', '433', '692', '1005', '764', '41', '308', '531', '485', '571', '807', '267', '1028', '840', '941', '905', '667', '179', '611', '213', '99', '579', '792', '628', '706', '254', '455', '459', '352', '107', '251', '578', '294', '241', '463', '625', '951', '73', '717', '331', '345', '739', '465', '567', '643', '936', '15', '439', '629', '78', '899', '230', '489', '207', '894', '1015', '743', '355', '26', '255', '478', '989', '990', '753', '217', '595', '645', '135', '187', '260', '479', '835', '895', '400', '327', '548', '236', '957', '494', '874', '385', '271', '663', '360', '730', '735', '856', '247', '240', '798', '450', '289', '427', '452', '833', '940', '859', '998', '504', '741', '587', '128', '952', '756', '563', '804', '451', '938', '297', '19', '766', '252', '719', '133', '889', '917', '937', '580', '94', '887', '127', '137', '687', '47', '964', '524', '488', '616', '759', '931', '1024', '775', '144', '440', '231', '927', '415', '279', '20', '288', '849', '676', '819', '898', '435', '515', '641', '707', '984', '88', '300', '320', '618', '404', '366', '649', '808', '608', '553', '863', '434', '148', '382', '243', '903', '883', '476', '780', '85', '1020', '122', '698', '968', '98', '265', '166', '305', '309', '604', '742', '33', '424', '371', '556', '881', '811', '880', '636', '672', '304', '413', '586', '803', '256', '857', '547', '280', '734', '528', '176', '446', '77', '884', '994', '814', '981', '503', '68', '996', '980', '278', '318', '425', '130', '188', '170', '341', '180', '174', '282', '568', '86', '613', '276', '112', '274', '848'] not in index"
```

**Comment by ngupta23** [comment]
Could you try converting the test data frame columns to `string` before feeding to the setup function? Does that solve the problem?

**Comment by ngupta23** [comment]
So this is actually a bug then. I think somewhere in the train data columns are being coerced into strings but not for the test data. We will have a look into this.

**Comment by moezali1** [comment]
@Yard1 @tvdboom This is something we should take care of in the current version (next release 2.3.7) as well as 3.0.

**Comment by tvdboom** [comment]
I pushed a fix for 3.0

**Comment by moezali1** [comment]
Thanks @tvdboom

**Comment by ngupta23** [comment]
@tvdboom Can we close this now?

**Comment by ngupta23** [comment]
@tvdboom It looks like the issue still exists on the `develop` branch

```python
!pip install git+https://github.com/pycaret/pycaret.git@develop

import pandas as pd
from sktime.datasets import load_arrow_head

# Load all arrow head
arrow_train_X, arrow_train_y = load_arrow_head(split="train", return_type="numpy2d")
arrow_test_X, arrow_test_y = load_arrow_head(split="test", return_type="numpyflat")

train_X_pd = pd.DataFrame(arrow_train_X)
train_y_pd = pd.DataFrame({"target": arrow_train_y})
test_X_pd = pd.DataFrame(arrow_test_X)
test_y_pd = pd.DataFrame({"target": arrow_test_y})

train_data = pd.concat([train_X_pd, train_y_pd], axis=1)
test_data = pd.concat([test_X_pd, test_y_pd], axis=1)

# Needed due to another bug in pycaret where test data columns are not coerced to string but train columns are
# train_data.columns = [str(col) for col in train_data.columns]
# test_data.columns = [str(col) for col in test_data.columns]

print(train_data.shape, test_data.shape)

from pycaret.classification import ClassificationExperiment
exp1 = ClassificationExperiment()
exp1.setup(data = train_data, test_data=test_data, target="target")
print(exp1.X_train.shape, exp1.X_test.shape)
```

The shape of X_train (number of columns) is doubled since the test columns are not coerced into string but the train columns are coerced into string.

![image](https://user-images.githubusercontent.com/33585645/167725419-7aeb43c8-6018-478f-ae3f-04dc33818e78.png)

**Comment by ngupta23** [comment]
This has been fixed by https://github.com/pycaret/pycaret/pull/2530, hence closing.
