### ISSUE TITLE
[BUG]: imputation_type='iterative' error in predict model with test data

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2600]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

when i try to predict data with test dataset with imputation_type='iterative' in setup i get an error.

I tested the same code in pycaret 2.3.10 and it works.

### Reproducible Example

```python
import pandas as pd
import pycaret

#titanic datasets (from kaggle competition)
#https://www.kaggle.com/competitions/titanic/data
train_data = pd.read_csv("train.csv")
teste_data = pd.read_csv("test.csv")

from pycaret.classification import *
s = setup(data=train_data, target='Survived', use_gpu=True, fold=5, imputation_type='iterative')

best_model = create_model('lightgbm')

final_model = finalize_model(best_model)

predictions = predict_model(final_model, data=teste_data)
predictions

output = pd.DataFrame({'PassengerId': predictions.PassengerId, 'Survived': predictions.Label})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")
```

### Expected Behavior

no errors, save file my_submission.csv and print "Your submission was successfully saved!"

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [17], in <cell line: 2>()
      1 #verificar modelo nos dados para teste
----> 2 predictions = predict_model(final_model, data=teste_data)
      3 predictions

File ~\anaconda3\lib\site-packages\pycaret\classification\functional.py:2073, in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose)
   2070 if experiment is None:
   2071     experiment = _EXPERIMENT_CLASS()
-> 2073 return experiment.predict_model(
   2074     estimator=estimator,
   2075     data=data,
   2076     probability_threshold=probability_threshold,
   2077     encoded_labels=encoded_labels,
   2078     raw_score=raw_score,
   2079     drift_report=drift_report,
   2080     round=round,
   2081     verbose=verbose,
   2082 )

File ~\anaconda3\lib\site-packages\pycaret\classification\oop.py:2634, in ClassificationExperiment.predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose)
   2561 def predict_model(
   2562     self,
   2563     estimator,
   (...)
   2570     verbose: bool = True,
   2571 ) -> pd.DataFrame:
   2573     """
   2574     This function predicts ``Label`` and ``Score`` (probability of predicted
   2575     class) using a trained model. When ``data`` is None, it predicts label and
   (...)
   2631 
   2632     """
-> 2634     return super().predict_model(
   2635         estimator=estimator,
   2636         data=data,
   2637         probability_threshold=probability_threshold,
   2638         encoded_labels=encoded_labels,
   2639         raw_score=raw_score,
   2640         drift_report=drift_report,
   2641         round=round,
   2642         verbose=verbose,
   2643     )

File ~\anaconda3\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:4828, in _SupervisedExperiment.predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, ml_usecase, preprocess)
   4826 data = data[X_columns]  # Ignore all column but the originals
   4827 if preprocess:
-> 4828     X_test_ = pipeline.transform(
   4829         X=data, y=(target if preprocess != "features" else None)
   4830     )
   4831     if final_step:
   4832         pipeline.steps.append(final_step)

File ~\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:200, in Pipeline.transform(self, X, y)
    196 def transform(self, X=None, y=None):
    197     for _, _, transformer in self._iter(
    198         with_final=hasattr(self._final_estimator, "transform")
    199     ):
--> 200         X, y = _transform_one(transformer, X, y)
    202     return variable_return(X, y)

File ~\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:46, in _transform_one(transformer, X, y)
     44 if "y" in signature(transformer.transform).parameters:
     45     args.append(y)
---> 46 output = transformer.transform(*args)
     48 if isinstance(output, tuple):
     49     X, y = output[0], output[1]

File ~\anaconda3\lib\site-packages\pycaret\internal\preprocess\transformers.py:207, in TransfomerWrapper.transform(self, X, y)
    204     elif "X" not in transform_params:
    205         return X, y
--> 207 output = self.transformer.transform(*args)
    209 # Transform can return X, y or both
    210 if isinstance(output, tuple):

File ~\anaconda3\lib\site-packages\pycaret\internal\preprocess\iterative_imputer.py:408, in IterativeImputer.transform(self, X)
    406     for col in X.select_dtypes("category").columns:
    407         X[col] = X[col].cat.rename_categories(self.mappings_[col])
--> 408 Xt = super().transform(X)
    409 if self.mappings_:
    410     Xt = _inverse_map_pd(Xt, self.mappings_, self.feature_names_in_)

File ~\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:725, in IterativeImputer.transform(self, X)
    708 """Impute all missing values in `X`.
    709 
    710 Note that this is stochastic, and that if `random_state` is not fixed,
   (...)
    721      The imputed input data.
    722 """
    723 check_is_fitted(self)
--> 725 X, Xt, mask_missing_values, complete_mask = self._initial_imputation(X)
    727 X_indicator = super()._transform_indicator(complete_mask)
    729 if self.n_iter_ == 0 or np.all(mask_missing_values):

File ~\anaconda3\lib\site-packages\pycaret\internal\preprocess\iterative_imputer.py:173, in IterativeImputer._initial_imputation(self, X, in_fit)
    170 else:
    171     force_all_finite = True
--> 173 X = self._validate_data(
    174     X,
    175     dtype=FLOAT_DTYPES,
    176     order="F",
    177     reset=in_fit,
    178     force_all_finite=force_all_finite,
    179 )
    180 _check_inputs_dtype(X, self.missing_values)
    182 X_missing_mask = _get_mask(X, self.missing_values)

File ~\anaconda3\lib\site-packages\sklearn\base.py:577, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, **check_params)
    575     raise ValueError("Validation should be done on X, y or both.")
    576 elif not no_val_X and no_val_y:
--> 577     X = check_array(X, input_name="X", **check_params)
    578     out = X
    579 elif no_val_X and not no_val_y:

File ~\anaconda3\lib\site-packages\sklearn\utils\validation.py:856, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
    854         array = array.astype(dtype, casting="unsafe", copy=False)
    855     else:
--> 856         array = np.asarray(array, order=order, dtype=dtype)
    857 except ComplexWarning as complex_warning:
    858     raise ValueError(
    859         "Complex data not supported\n{}\n".format(array)
    860     ) from complex_warning

File ~\anaconda3\lib\site-packages\pandas\core\generic.py:2064, in NDFrame.__array__(self, dtype)
   2063 def __array__(self, dtype: npt.DTypeLike | None = None) -> np.ndarray:
-> 2064     return np.asarray(self._values, dtype=dtype)

ValueError: could not convert string to float: 'Wilkes, Mrs. James (Ellen Needs)'
```

### Installed Versions

<details>
python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\celes\anaconda3\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 61.2.0
             pycaret: 3.0.0
             ipython: Installed but version unavailable
          ipywidgets: 7.6.5
                tqdm: 4.64.0
               numpy: 1.21.5
              pandas: 1.4.2
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.4.1
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.1
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.6.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
</details>

**Comment by tvdboom** [comment]
This is fixed in #2606. It will be available as soon as the PR is closed

**Comment by celestinoxp** [comment]
> This is fixed in #2606. It will be available as soon as the PR is closed

After commit [Merge pull request](https://github.com/pycaret/pycaret/commit/90a4cff5d70333fc7548d4fbb620c75008bd3e95) https://github.com/pycaret/pycaret/pull/2606 [from pycaret/fix_imbalance], problem persists...

**Comment by tvdboom** [comment]
@celestinoxp I can't reproduce the error. Could you share your `train.csv` and `test.csv`?

**Comment by celestinoxp** [comment]
> @celestinoxp I can't reproduce the error. Could you share your `train.csv` and `test.csv`?
[test.csv](https://github.com/pycaret/pycaret/files/8837502/test.csv)
[train.csv](https://github.com/pycaret/pycaret/files/8837503/train.csv)

**Comment by celestinoxp** [comment]
I tested now, in Google Colab with same error.
To reproduce exactly:

1ºst - i used command to install pycaret: !pip install -U git+https://github.com/pycaret/pycaret.git@develop
2ºnd - upload files train.csv and test.csv to colab
3ºrd - paste code in cell:
import pandas as pd
import pycaret

#titanic datasets (from kaggle competition)
#https://www.kaggle.com/competitions/titanic/data
train_data = pd.read_csv("train.csv")
teste_data = pd.read_csv("test.csv")

from pycaret.classification import *
s = setup(data=train_data, target='Survived', use_gpu=True, fold=5, imputation_type='iterative')

best_model = create_model('lightgbm')

final_model = finalize_model(best_model)

predictions = predict_model(final_model, data=teste_data)
predictions

output = pd.DataFrame({'PassengerId': predictions.PassengerId, 'Survived': predictions.Label})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")



Then after 7 min 17 sec show error:




---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-2-f95ada947207>](https://localhost:8080/#) in <module>()
     14 final_model = finalize_model(best_model)
     15 
---> 16 predictions = predict_model(final_model, data=teste_data)
     17 predictions
     18 

11 frames
[/usr/local/lib/python3.7/dist-packages/pycaret/classification/functional.py](https://localhost:8080/#) in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose)
   2086         drift_report=drift_report,
   2087         round=round,
-> 2088         verbose=verbose,
   2089     )
   2090 

[/usr/local/lib/python3.7/dist-packages/pycaret/classification/oop.py](https://localhost:8080/#) in predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose)
   2696             drift_report=drift_report,
   2697             round=round,
-> 2698             verbose=verbose,
   2699         )
   2700 

[/usr/local/lib/python3.7/dist-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py](https://localhost:8080/#) in predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, ml_usecase, preprocess)
   4873                 X_test_ = pipeline.transform(
   4874                     X=data,
-> 4875                     y=(target if preprocess != "features" else None),
   4876                 )
   4877                 if final_step:

[/usr/local/lib/python3.7/dist-packages/pycaret/internal/pipeline.py](https://localhost:8080/#) in transform(self, X, y, filter_train_only)
    159             filter_train_only=filter_train_only,
    160         ):
--> 161             X, y = _transform_one(transformer, X, y)
    162 
    163         return variable_return(X, y)

[/usr/local/lib/python3.7/dist-packages/pycaret/internal/pipeline.py](https://localhost:8080/#) in _transform_one(transformer, X, y)
     44     if "y" in signature(transformer.transform).parameters:
     45         args.append(y)
---> 46     output = transformer.transform(*args)
     47 
     48     if isinstance(output, tuple):

[/usr/local/lib/python3.7/dist-packages/pycaret/internal/preprocess/transformers.py](https://localhost:8080/#) in transform(self, X, y)
    206                 return X, y
    207 
--> 208         output = self.transformer.transform(*args)
    209 
    210         # Transform can return X, y or both

[/usr/local/lib/python3.7/dist-packages/pycaret/internal/preprocess/iterative_imputer.py](https://localhost:8080/#) in transform(self, X)
    406             for col in X.select_dtypes("category").columns:
    407                 X[col] = X[col].cat.rename_categories(self.mappings_[col])
--> 408         Xt = super().transform(X)
    409         if self.mappings_:
    410             Xt = _inverse_map_pd(Xt, self.mappings_, self.feature_names_in_)

[/usr/local/lib/python3.7/dist-packages/sklearn/impute/_iterative.py](https://localhost:8080/#) in transform(self, X)
    722         check_is_fitted(self)
    723 
--> 724         X, Xt, mask_missing_values, complete_mask = self._initial_imputation(X)
    725 
    726         X_indicator = super()._transform_indicator(complete_mask)

[/usr/local/lib/python3.7/dist-packages/pycaret/internal/preprocess/iterative_imputer.py](https://localhost:8080/#) in _initial_imputation(self, X, in_fit)
    176             order="F",
    177             reset=in_fit,
--> 178             force_all_finite=force_all_finite,
    179         )
    180         _check_inputs_dtype(X, self.missing_values)

[/usr/local/lib/python3.7/dist-packages/sklearn/base.py](https://localhost:8080/#) in _validate_data(self, X, y, reset, validate_separately, **check_params)
    564             raise ValueError("Validation should be done on X, y or both.")
    565         elif not no_val_X and no_val_y:
--> 566             X = check_array(X, **check_params)
    567             out = X
    568         elif no_val_X and not no_val_y:

[/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py](https://localhost:8080/#) in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    744                     array = array.astype(dtype, casting="unsafe", copy=False)
    745                 else:
--> 746                     array = np.asarray(array, order=order, dtype=dtype)
    747             except ComplexWarning as complex_warning:
    748                 raise ValueError(

[/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __array__(self, dtype)
   1991 
   1992     def __array__(self, dtype: NpDtype | None = None) -> np.ndarray:
-> 1993         return np.asarray(self._values, dtype=dtype)
   1994 
   1995     def __array_wrap__(

ValueError: could not convert string to float: 'Wilkes, Mrs. James (Ellen Needs)'

**Comment by ngupta23** [comment]
@tvdboom could you have a look please? Thanks!

**Comment by ngupta23** [comment]
It is not working with the RC2 release?

**Comment by celestinoxp** [comment]
i found something... i'm finding why "model_predict" works with train_data (but is not right, because we need predict unseen data).
However i found in transformed data column "Name" should be different numbers, right? But all transformed names are equal... this is right?
![teste_pycaret](https://user-images.githubusercontent.com/41735311/172665277-823ac6c5-dddd-43c7-b418-ca16d8d11080.png)

**Comment by Yard1** [comment]
Fixed in 5f7c6d26656dc06bf1347b41519dfc6ebaeb3b84 but needs https://github.com/pycaret/pycaret/pull/2647 to be also merged for the example to work
