### ISSUE TITLE
[INSTALL]:  Could not build wheels for scikit-learn which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by SSMK-wq** [pycaret/pycaret#3067]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19044-SP0

### Installation Method

pip install

### pycaret Version

I assume pip install does the latest version

### Python Version

Python 3.9.12

### Description

I tried the below 

`pip install pycaret`

I am getting this error:

ERROR: Could not build wheels for scikit-learn which use PEP 517 and cannot be installed directly

I already tried

`pip install pep517`

and

`pip install p5py`

and also tried the below

```
conda install bottleneck
pip install pycaret
```

I already followed solutions from SO post [here](https://stackoverflow.com/questions/71419537/error-could-not-build-wheels-for-scikit-learn-which-use-pep-517-and-cannot-be-i) and previous issue here [1461 (https://github.com/pycaret/pycaret/issues/1461) and [1540](https://github.com/pycaret/pycaret/issues/1540)

I keep getting the below error

```
Successfully built cufflinks gensim pyLDAvis pyod umap-learn databricks-cli pynndescent
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects
```

So, I tried the beta version

`pip install pycaret-ts-alpha`

and that also resulted in the below error

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mljar-supervised 0.11.2 requires catboost>=0.24.4, which is not installed.
Successfully installed category-encoders-2.5.1.post0 lightgbm-3.3.3 llvmlite-0.38.1 numba-0.55.2 pycaret-ts-alpha-3.0.0.dev1649017462 pyod-1.0.6 scikit-plot-0.3.7 sktime-0.10.1 tbats-1.1.1 yellowbrick-1.5
```

I always wanted to try this package for the past 6 months but keep going back due to installation issue. This package seems very useful but for some reason, it never works in my system. Only option is to downgrade my python version? from 3.9.12 to 3.8? but afraid that it may affect other packages in the system

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by celestinoxp** [comment]
Try install pycaret 3 with this command `pip install --pre pycaret -U`

**Comment by moezali1** [comment]
Installing pycaret with `pip install --pre pycaret` should resolve the issue. Make sure to restart the kernel after installation.

**Comment by SSMK-wq** [comment]
@moezali1 - This resulted in another error as shown below

` ImportError: cannot import name '_joblib_parallel_args' from 'sklearn.utils.fixes' (C:\Users\Akshay\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\fixes.py)`

**Comment by ngupta23** [comment]
Are you installing this in a fresh environment?

**Comment by SSMK-wq** [comment]
@ngupta23 - I uninstalled my old version and redid from beginning. I followed the below steps

```
pip uninstall pycaret
pip install --pre pycaret
restart the kernel in jupyter notebook multiple times
close and reopen the jupyter notebook
```

**Comment by SSMK-wq** [comment]
@ngupta23 - Just to clarify the the above error message is not during installation

This happens when I type the below line

`from pycaret.regression import *` (import pycaret works fine though)

**Comment by ngupta23** [comment]
That is not the same though. You need to create **a new conda environment**, then install pycaret from scratch in that conda environment using the command mentioned. 

The issue you have is that somehow you have an older version of sklearn installed and that is causing issues (even after installing pycaret). Following the recommended instructions should resolve it.

**Comment by SSMK-wq** [comment]
@ngupta23 - No, I tried with latest scikit-learn version as well. This error doesn't go away. I still get the same joblib error when I try to do the below line

`from pycaret.regression import *`

**Comment by ngupta23** [comment]
Can you post the output of the following command?

```python
from pycaret import show_versions
show_versions()
```

**Comment by SSMK-wq** [comment]
@ngupta23 - Please find the details below

```
System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Aks\Anaconda3\python.exe
   machine: Windows-10-10.0.19044-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 61.2.0
             pycaret: 3.0.0rc4
             IPython: 8.2.0
          ipywidgets: 7.6.5
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 2.11.3
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.3
                pyod: 1.0.6
            imblearn: 0.9.0
   category_encoders: 2.5.1.post0
            lightgbm: 3.3.3
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.6.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.13.4
               tbats: 1.1.1
            pmdarima: 1.8.4
              psutil: 5.8.0

PyCaret optional dependencies:
                shap: 0.36.0
           interpret: Not installed
                umap: Not installed
    pandas_profiling: 3.1.0
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.4.2
            catboost: 1.1.1
              kmodes: Not installed
             mlxtend: 0.21.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: 1.13.0
            hyperopt: 0.2.7
              optuna: 2.10.0
               skopt: 0.9.0
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
                nltk: 3.7
            pyLDAvis: Not installed
              gensim: 4.1.2
               spacy: 3.4.3
           wordcloud: 1.8.1
            textblob: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
```

**Comment by ngupta23** [comment]
The installation seems to be correct. Can you paste the complete error stack that you are getting? We need to trace the internal code that is causing this and need the complete error trace for this.
