### ISSUE TITLE
Stratification issue while splitting an imbalanced dataset

### ISSUE THREAD

**Issue by vishal-subedi** [pycaret/pycaret#84]
Hey, I was trying to implement an imbalanced dataset while I got this error:

_-> 1439         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1-train_size, stratify=y, random_state=seed)
   1440         progress.value += 1
   1441 

~\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py in train_test_split(*arrays, **options)
   2139                      random_state=random_state)
   2140 
-> 2141         train, test = next(cv.split(X=arrays[0], y=stratify))
   2142 
   2143     return list(chain.from_iterable((_safe_indexing(a, train),

~\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py in split(self, X, y, groups)
   1327         """
   1328         X, y, groups = indexable(X, y, groups)
-> 1329         for train, test in self._iter_indices(X, y, groups):
   1330             yield train, test
   1331 

~\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py in _iter_indices(self, X, y, groups)
   1657         class_counts = np.bincount(y_indices)
   1658         if np.min(class_counts) < 2:
-> 1659             raise ValueError("The least populated class in y has only 1"
   1660                              " member, which is too few. The minimum"
   1661                              " number of groups for any class cannot"_

**ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.**

I guess there should be an option to whether use the stratify option or not as the stratification parameter in the train_test_split is causing a problem while handling an imbalanced dataset.

**Comment by moezali1** [comment]
Can you share the dataset so we can reproduce the issue.

**Comment by vishal-subedi** [comment]
> 
> 
> Can you share the dataset so we can reproduce the issue.

I am afraid I can't do so as I am working on a real life dataset and comes under the nondisclosure part of the project. In order to reproduce the issue, an imbalanced dataset could always be synthesized, or in that case, any other imbalanced dataset could serve the purpose.

**Comment by pycaret** [comment]
ok one question. Are there less than 10 instances of minority class?

**Comment by vishal-subedi** [comment]
> 
> 
> ok one question. Are there less than 10 instances of minority class?

No, there are around 2500 instances of the minority class in the complete dataset(test+train)

**Comment by pycaret** [comment]
Hi. 

We are adding shuffle parameter in next release. It should solve this problem. 

Thanks.

**Comment by pycaret** [comment]
Marking this as an enhancement.

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly".

New parameter **folds_shuffle** is now added in setup. By default it is set to False.

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.

**Comment by vishal-subedi** [comment]
Yeah..surely. Just give me a couple of days

**Comment by nkalhan** [comment]
any update.. i still have this error: 

from pycaret.classification import *
clf1 = setup(data = data, target = 'Division', high_cardinality_features= ['Account Name'])

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-16b4a43fd42a> in <module>
      1 from pycaret.classification import *
----> 2 clf1 = setup(data = data, target = 'Division', folds_shuffle=False , high_cardinality_features= ['Account Name'])

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
   1772             if html_param:
   1773                 update_display(monitor, display_id = 'monitor')
-> 1774         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1-train_size, stratify=y, random_state=seed, shuffle=data_split_shuffle)
   1775         progress.value += 1
   1776 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_split.py in train_test_split(*arrays, **options)
   2150                      random_state=random_state)
   2151 
-> 2152         train, test = next(cv.split(X=arrays[0], y=stratify))
   2153 
   2154     return list(chain.from_iterable((_safe_indexing(a, train),

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_split.py in split(self, X, y, groups)
   1339         """
   1340         X, y, groups = indexable(X, y, groups)
-> 1341         for train, test in self._iter_indices(X, y, groups):
   1342             yield train, test
   1343 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_split.py in _iter_indices(self, X, y, groups)
   1666         class_counts = np.bincount(y_indices)
   1667         if np.min(class_counts) < 2:
-> 1668             raise ValueError("The least populated class in y has only 1"
   1669                              " member, which is too few. The minimum"
   1670                              " number of groups for any class cannot"

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

**Comment by nkalhan** [comment]
i tried the recommendation of label class atleast 2... i still have this error:

from pycaret.classification import *
reg1 = setup(data, target='Division', high_cardinality_features=['Account Name'], train_size=0.2 , folds_shuffle=True)

ValueError Traceback (most recent call last)
in
1 from pycaret.classification import *
----> 2 reg1 = setup(data, target='Division', high_cardinality_features=['Account Name'], train_size=0.2 , folds_shuffle=True)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
1453
1454 X_, X__, y_, y__ = train_test_split(X, y, test_size=1-i, stratify=y, random_state=seed, shuffle=data_split_shuffle)
-> 1455 X_train, X_test, y_train, y_test = train_test_split(X_, y_, test_size=0.3, stratify=y_, random_state=seed, shuffle=data_split_shuffle)
1456 model.fit(X_train,y_train)
1457 pred_ = model.predict(X_test)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection_split.py in train_test_split(*arrays, **options)
2150 random_state=random_state)
2151
-> 2152 train, test = next(cv.split(X=arrays[0], y=stratify))
2153
2154 return list(chain.from_iterable((_safe_indexing(a, train),

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection_split.py in split(self, X, y, groups)
1339 """
1340 X, y, groups = indexable(X, y, groups)
-> 1341 for train, test in self._iter_indices(X, y, groups):
1342 yield train, test
1343

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection_split.py in _iter_indices(self, X, y, groups)
1666 class_counts = np.bincount(y_indices)
1667 if np.min(class_counts) < 2:
-> 1668 raise ValueError("The least populated class in y has only 1"
1669 " member, which is too few. The minimum"
1670 " number of groups for any class cannot"

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

**Comment by pycaret** [comment]
@nkalhan This error is caused by too few instances for label classes. `StratifiedKFold` fails when `folds` > `number of instances in class`.
